### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by callree** [mobilecoinofficial/developer-grants#4]
Using Git

To use Git on the command line, you will need to download, install, and configure Git on your computer. You can also install GitHub CLI to use GitHub from the command line. For more information, see "[About GitHub CLI](https://docs.github.com/en/github-cli/github-cli/about-github-cli)."

If you want to work with Git locally, but do not want to use the command line, you can instead download and install the [GitHub Desktop](https://desktop.github.com/) client. For more information, see "[Installing and configuring GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop)."

If you do not need to work with files locally, GitHub lets you complete many Git-related actions directly in the browser, including:

**Comment by opencolin** [comment]
I think this was opened in error.

**Comment by callree** [comment]
뭔지도 제대로 실수한것같아서 알았을때 닫게 되었다
